# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY eti-assignment-2-firebase-adminsdk-6r9lk-85fb98eda4.json /app/

COPY *.go ./

RUN go build -o /chatting

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /chatting /chatting
COPY --from=build /app/eti-assignment-2-firebase-adminsdk-6r9lk-85fb98eda4.json /

EXPOSE 5053

USER nonroot:nonroot

ENTRYPOINT ["/chatting"]
