# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY eti-assignment-2-firebase-adminsdk-6r9lk-85fb98eda4.json /app/

COPY *.go ./

RUN go build -o /subject

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /subject /subject

EXPOSE 5051

USER nonroot:nonroot

ENTRYPOINT ["/subject"]
